### ISSUE TITLE
Invalid Schema: data.properties['active'].should be an array

### ISSUE THREAD

**Issue by bryanbill** [bryanbill/soloo#2]
Error: schema is invalid: data.properties['isActive'].required should be array
   at Ajv.validateSchema (/home/vader/projects/startups/soloo/node_modules/ajv/lib/ajv.js:178:16)
   at Ajv._addSchema (/home/vader/projects/startups/soloo/node_modules/ajv/lib/ajv.js:307:10)                                                                              
   at Ajv.compile (/home/vader/projects/startups/soloo/node_modules/ajv/lib/ajv.js:113:24)
   at UsersController.validate (/home/vader/projects/startups/soloo/node_modules/@foal/core/lib/common/hooks/validate-body.hook.js:22:55)

**Comment by bryanbill** [comment]
Fixed
